jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/sanguo_game?useUnicode=true&characterEncoding=utf8
jdbc.user=root
jdbc.password=EghgTJGqPmZ9RQiW
useUnicode=true
characterEncoding=UTF-8